name: Deploy Static Portal

on:
  workflow_dispatch:  
  push:
    branches: 
      - master 
      
jobs:
  generate-portal:
    runs-on: ubuntu-latest

    steps:
       
    - uses: actions/checkout@v1
      name : checkout-repo
      id: checkout-repo  
      
    - name: Zip files
      run: zip -qq -r portal-input.zip .
      
    - name: Call build endpoint
      run: curl -X POST --url 'https://www.apimatic.io/api/portal' -H 'Authorization:X-Auth-Key $wosykkoUIhcBeBkhwxgjsxjl_qeDXuNWWV9Ikpuk_0RxmW7zrSkkUNmlwvCKHJGR' -F 'file=@portal-input.zip' -o portal-output.zip
      
    - name: list 
      run: ls
      
    - name: Extract generated Portal
      run: unzip -qq portal-output.zip -d static-portal
      
    - name: list 
      run: ls
      

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.2
      with:
        publish-dir: './static-portal'
        production-branch: master
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: false
        enable-commit-comment: true
        overwrites-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.foVQYxIAPmuWRYa3sZ_g_te75CtIo6R8rLEgGSU1x6I }}
        NETLIFY_SITE_ID: ${{ secrets.2f1a2ad1-6937-4731-9c60-e8e8d480be71 }}
      timeout-minutes: 1
    
      
